In [3]:
import pandas as pd
from sklearn.linear_model import LinearRegression
from word2number import w2n
import numpy as np

In [2]:
pip install word2number

  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Created wheel for word2number: filename=word2number-1.1-py3-none-any.whl size=5589 sha256=034cc0bf08602fea6d7cc5b85aff80997c6aebf3f485bd4012f9ab8e239a16f9
  Stored in directory: c:\users\ranjani\appdata\local\pip\cache\wheels\5b\79\fb\d25928e599c7e11fe4e00d32048cd74933f34a74c633d2aea6
Successfully built word2number
Note: you may need to restart the kernel to use updated packages.


In [4]:
df = pd.read_csv(r'C:\Users\Ranjani\Downloads\hiring.csv')

In [5]:
df.head(5)

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000

In [8]:
df['experience']= df['experience'].fillna('Zero')

In [9]:
df.head(5)

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       Zero                    8.0                           9      50000
1       Zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000

In [10]:
df.isna()

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       False                  False                       False      False
1       False                  False                       False      False
2       False                  False                       False      False
3       False                  False                       False      False
4       False                  False                       False      False
5       False                  False                       False      False
6       False                   True                       False      False
7       False                  False                       False      False

In [12]:
df.experience = df.experience.apply(w2n.word_to_num)
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    NaN                           7      72000
7          11                    7.0                           8      80000

In [14]:
df.rename(columns = {'test_score(out of 10)':'test_score'},inplace=True)

In [16]:
import math
mval = math.floor(df.test_score.mean())

In [17]:
df.test_score = df.test_score.fillna(mval)

In [18]:
df

experience  test_score  interview_score(out of 10)  salary($)
0           0         8.0                           9      50000
1           0         8.0                           6      45000
2           5         6.0                           7      60000
3           2        10.0                          10      65000
4           7         9.0                           6      70000
5           3         7.0                          10      62000
6          10         7.0                           7      72000
7          11         7.0                           8      80000

In [19]:
rmodel = LinearRegression()
rmodel.fit(df[['experience','test_score','interview_score(out of 10)']],df['salary($)'])


LinearRegression()

In [21]:
rmodel.predict([[7,11,7.0]])

C:\Users\Ranjani\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([74915.31261189])

In [22]:
rmodel.predict([[2,9,6]])

C:\Users\Ranjani\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([53713.86677124])

In [23]:
rmodel.coef_

array([2922.26901502, 2221.30909959, 2147.48256637])

In [24]:
rmodel.intercept_

14992.65144669314

In [25]:
2922.26901502*2+2221.30909959*9+2147.48256637*6 + 14992.65144669314

53713.86677126314